### ISSUE TITLE
Can't run `blt setup:all` outside of VM

### ISSUE THREAD

**Issue by danielnitschelc** [acquia/blt#1745]
My system information:
* Operating system type: macOS Sierra
* Operating system version: 10.12.4
* BLT version: 8.9.0-rc1

Output of `blt doctor`:
```
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/myproject/docroot                                                         |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/myproject/config/default                                                  |
|  - %config-vcs       | sites/default/files/config_cn4hTV5qbaNNLE4HqzDLu1FO8y2TlPtKFe2FSSLMrmBSs5GmwIdsu |
|                      | 6v1HQmHgi98mMhqTcRLGA/sync                                                       |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/myproject/files-private                                                   |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.9.0-rc1                                                                        |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/myproject/config/default                                                  |
| config-vcs           | sites/default/files/config_cn4hTV5qbaNNLE4HqzDLu1FO8y2TlPtKFe2FSSLMrmBSs5GmwIdsu |
|                      | 6v1HQmHgi98mMhqTcRLGA/sync                                                       |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | default                                                                          |
| db-password          | drupal                                                                           |
| db-port              | 3306                                                                             |
| db-status            | Connected                                                                        |
| db-username          | drupal                                                                           |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.3.4                                                                            |
| drush-alias-files    | /var/www/myproject/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/myproject/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
|                      | /var/www/myproject/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
| drush-conf           | /var/www/myproject/drush/drushrc.php                                               |
| drush-script         | /var/www/myproject/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                             |
| drush-version        | 8.1.12                                                                           |
| files                | sites/default/files                                                              |
| install-profile      | lightning                                                                        |
| local-drushrc        | /var/www/myproject/docroot/sites/default/local.drushrc.php                         |
| local-settings       | /var/www/myproject/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/7.1/cli/php.ini                                                         |
| php-os               | Linux                                                                            |
| private              | /var/www/myproject/files-private                                                   |
| root                 | /var/www/myproject/docroot                                                         |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | stark                                                                            |
| themes               | themes                                                                           |
| uri                  | http://local.myproject.com                                                         |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+---------------------------------------------------------+
| Check                    | Outcome                                                 |
+--------------------------+---------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                          |
| checkCoreExists          | Drupal core exists                                      |
| checkSettingsFile        | BLT settings are included in settings file.             |
| checkLocalSettingsFile   | Found your local settings file.                         |
| checkLocalDrushFile      | Found your local drush settings file.                   |
| checkUri                 | $options['uri'] is set.                                 |
| checkUriResponse         | Received a response from site http://local.myproject.com. |
| checkFileSystem:%files   | Public files directory is writable.                     |
| checkFileSystem:%private | Private files directory is writable.                    |
| checkFileSystem:%temp    | Temporary files directory is writable.                  |
| checkDbConnection        | Connected to database.                                  |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                          |
| checkDrupalInstalled     | Drupal is installed.                                    |
| checkCaching:page        | Drupal cache is disabled.                               |
| checkCaching:css         | CSS preprocessing is disabled.                          |
| checkCaching:js          | JS preprocessing is disabled.                           |
| checkCiConfig            | Git remotes are set in project.yml.                     |
| checkComposer:require    | acquia/blt is in composer.json's require object.        |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.     |
| checkBehat:exists        | Behat local settings file exists.                       |
| checkProjectYml:keys     | project.yml has no deprecated keys.                     |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set          |
+--------------------------+---------------------------------------------------------+

```

When I run this command (outside of the VM):
```
blt setup
```

I get the following output:
```
> frontend:setup
Executing frontend-setup target hook...
[ExecStack] echo 'No frontend setup configured'
[ExecStack] Running echo 'No frontend setup configured' in /vagrant/docroot
No frontend setup configured
[ExecStack] Done in 0.016s
> frontend:build
Executing frontend-build target hook...
[ExecStack] echo 'No frontend build configured'
[ExecStack] Running echo 'No frontend build configured' in /vagrant/docroot
No frontend build configured
[ExecStack] Done in 0.008s
[error]  Command `frontend ` exited with code 113. 
[error]  Command `setup:build ` exited with code 1. 

```

And I expected this to happen:
I was hoping to be able to run `blt setup` outside of the VM as was previously possible. `blt setup` within the VM works ok.

This appears to be the commit that changed this behaviour:
https://github.com/acquia/blt/commit/55166711d54c03e3f1430f4b8cba48c50bed08d2#diff-9727651ebac3ee94b90cd5d0ac66c969

**Comment by grasmash** [comment]
Hm, the output that you've pasted doesn't seem to indicate that the command was run inside the VM. Can you paste the full output, and run the command with `-vvv` ? 

The `setup` command isn't tagged to run inside the VM, although all of the frontend commands are. 

I might consider this as a feature request. We can make vm execution dependent on a "vm.execute-inside" variable, which you could then set to true or false in your own project.local.yml.

**Comment by danielnitschelc** [comment]
> Hm, the output that you've pasted doesn't seem to indicate that the command was run inside the VM

I'm assuming you meant "outside the VM" here? Because it works fine inside the VM, just not outside. Can paste the full output if needed, but not till next week.

The biggest problem was I've been using the command outside the VM for the last couple of months, but it suddenly stopped working. No problems if it's only supposed to be run inside the VM, as long as it's clear running it outside the VM is not supported.

**Comment by grasmash** [comment]
So, when you are on the CLI outside the VM and you execute any frontend task, BLT should automatically SSH into the VM and execute the command for you there. Looks like that isn't happening here. I'd guess that it's due to your specific VM configuration. It's likely that a `blt vm:nuke` and `blt vm` would resolve it.

**Comment by thom8** [comment]
I'm able to consistently replicate this issue, when using `blt deploy` while the VM is running.

I've disabled any frontend scripts to isolate the issue.

Seems to only occur when the frontend script is invoked from another command, there's no issue running `blt frontend` directly.

```
[ExecStack] vagrant exec --tty 'blt frontend -vvv --define drush.alias=self'
[ExecStack] Running vagrant exec --tty 'blt frontend -vvv --define drush.alias=self' in /[****]
[Robo\Common\ProcessExecutor] Running vagrant status --machine-readable in /var/www/toll
[debug] Drupal VM is not initialized.
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> frontend:setup
Executing frontend-setup target hook...
[ExecStack] echo 'No pre-config-import configured.'
[ExecStack] Running echo 'No pre-config-import configured.' in /var/www/toll
No pre-config-import configured.
[ExecStack] Done in 0.004s
> frontend:build
Executing frontend-build target hook...
[ExecStack] echo 'No pre-config-import configured.'
[ExecStack] Running echo 'No pre-config-import configured.' in /var/www/toll
No pre-config-import configured.
[ExecStack] Done in 0.005s
0.372s total time elapsed.
[ExecStack] Done in 3.423s
[error]  Command `frontend ` exited with code 113.
```

**Comment by thom8** [comment]
This patch is a workaround -- https://github.com/thom8/blt/commit/7d6ce27b0b686da83d9a81e2695817cc20a5a771.patch

My perference is to run FED installs on the host and leverage caching, would be good if this could be optional per command.

**Comment by typhonius** [comment]
I did a little debugging on this:

- Default text for frontend-setup and frontend-build steps
- Switching order in which blt frontend invokes commands still leads to error
- Running blt frontend on its own works 
- Running the vagrant exec commands for blt frontend work fine
- Removing tag for 'executeInDrupalVm' on the frontend function prevents error

Could it be the case that we're trying to execute things in a VM when we're already in a VM because both the frontend function, build function and setup function are all tagged with executeInDrupalVm? Having said that, I'd have thought the blt frontend command would have failed.

**Comment by grasmash** [comment]
I believe this is resolved by #1759

**Comment by grasmash** [comment]
So, I'm certain that `Command `frontend ` exited with code 113.` was caused by the bug that was fixed in #1759. Please re-open if the problem persists.

**Comment by danielnitschelc** [comment]
Neither https://github.com/acquia/blt/pull/1759/commits/f72aed10808127bd3064f0ab7ef153489aea5b93.patch, nor https://github.com/thom8/blt/commit/7d6ce27b0b686da83d9a81e2695817cc20a5a771.patch work for me, so maybe there is something up with my local system, or because I'm running rc1.

Here is what works for me on rc1:
```
diff --git a/src/Robo/Commands/Frontend/FrontendCommand.php b/src/Robo/Commands/Frontend/FrontendCommand.php
index 20e4e4dc..513a45ce 100644
--- a/src/Robo/Commands/Frontend/FrontendCommand.php
+++ b/src/Robo/Commands/Frontend/FrontendCommand.php
@@ -13,8 +13,6 @@ class FrontendCommand extends BltTasks {
    * Runs all frontend targets.
    *
    * @command frontend
-   *
-   * @executeInDrupalVm
    */
   public function frontend() {
     $this->invokeCommands([
@@ -27,8 +25,6 @@ public function frontend() {
    * Executes frontend-build target hook.
    *
    * @command frontend:build
-   *
-   * @executeInDrupalVm
    */
   public function build() {
     return $this->invokeHook('frontend-build');
@@ -38,8 +34,6 @@ public function build() {
    * Executes frontend-setup target hook.
    *
    * @command frontend:setup
-   *
-   * @executeInDrupalVm
    */
   public function setup() {
     return $this->invokeHook('frontend-setup');

```

**Comment by thom8** [comment]
@grasmash I can confirm that this has fixed my issue.

However, we'd still like to run the `frontend` build tasks on the host and still run behat tests inside the VM, is there a simple way to configure this?

rerolled patch in the mean time -- https://github.com/thom8/blt/commit/7d6ce27b0b686da83d9a81e2695817cc20a5a771.patch

**Comment by swichers** [comment]
I updated a project from an older version of BLT (8.7 branch) to 8.9rc2.

My frontend task was originally `npm install -g gulp && gulp`. I broke that out into two parts, `npm install -g gulp` and `gulp` based on the new frontend hooks. I was still having the 113 exit code issue, but manually running those commands outside/inside the vm worked fine.

What fixed the problem for me was rebuilding the vm per the blue informational text output after initially doing the update. Once I did that I saw that gulp was already being included as part of the VM, removed my npm install command, and my frontend build worked without issue.
