### ISSUE TITLE
Trouble getting a fully functional mutisite configuration with BLT.

### ISSUE THREAD

**Issue by pcsukardi** [acquia/blt#2710]
My system information:
* Operating system type: [Ubuntu]
* Operating system version: [16.04]
* BLT version: [9.0.5]

Output of `blt doctor`:
```
+---------------------------+-----------------------------------------------------+
| Property                  | Value                                               |
+---------------------------+-----------------------------------------------------+
| %paths.%root              | /var/www/test/docroot                               |
| %paths.%site              | sites/default                                       |
| %paths.%modules           | sites/all/modules                                   |
| %paths.%themes            | sites/all/themes                                    |
| %paths.%config-sync       | /var/www/test/config/default                        |
| %paths.%files             | sites/default/files                                 |
| %paths.%temp              | /tmp                                                |
| %paths.%private           | /var/www/test/files-private                         |
| admin-theme               | seven                                               |
| alias-searchpaths.0       | /home/vagrant/.drush/sites                          |
| alias-searchpaths.1       | /var/www/test/drush/sites                           |
| blt-version               | 9.0.5                                               |
| bootstrap                 | Successful                                          |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17          |
| config-sync               | /var/www/test/config/default                        |
| db-driver                 | mysql                                               |
| db-hostname               | localhost                                           |
| db-name                   | drupal                                              |
| db-password               | drupal                                              |
| db-port                   | 3306                                                |
| db-status                 | Connected                                           |
| db-username               | drupal                                              |
| drupal-settings-file      | sites/default/settings.php                          |
| drupal-version            | 8.5.1                                               |
| drush-alias-files.0       | /home/vagrant/.drush/sites/test.site.yml            |
| drush-alias-files.1       | /var/www/test/drush/sites/default.site.yml          |
| drush-alias-files.2       | /var/www/test/drush/sites/example.site.yml          |
| drush-alias-files.3       | /var/www/test/drush/sites/test.site.yml             |
| drush-conf.0              | /home/vagrant/.drush/drush.yml                      |
| drush-conf.1              | /var/www/test/vendor/drush/drush/drush.yml          |
| drush-conf.2              | /var/www/test/drush/drush.yml                       |
| drush-conf.3              | /var/www/test/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/test/vendor/bin/drush                      |
| drush-temp                | /tmp                                                |
| drush-version             | 9.2.1                                               |
| files                     | sites/default/files                                 |
| install-profile           | standard                                            |
| modules                   | sites/all/modules                                   |
| php-bin                   | /usr/bin/php7.1                                     |
| php-conf.0                | /etc/php/7.1/cli/php.ini                            |
| php-os                    | Linux                                               |
| private                   | /var/www/test/files-private                         |
| root                      | /var/www/test/docroot                               |
| site                      | sites/default                                       |
| stacks.drupal-vm.inited   | true                                                |
| stacks.dev-desktop.inited | false                                               |
| temp                      | /tmp                                                |
| theme                     | bartik                                              |
| themes                    | sites/all/themes                                    |
| uri                       | http://local.blted8.com                             |
+---------------------------+-----------------------------------------------------+
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri          | base_url in tests/behat/local.yml does not match the site    |
|                                      | URI.                                                         |
|                                      |   Behat base_url is set to                                   |
|                                      | http://local.test.com.                                       |
|                                      |   Drush site URI is set to                                   |
|                                      | http://local.blted8.com.                                     |
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse         | Did not get a response from http://local.blted8.com          |
|                                      | Is your *AMP stack running?                                  |
|                                      | Is your /etc/hosts file correctly configured?                |
|                                      | Is your web server configured to serve this URI from         |
|                                      | /var/www/test/docroot?                                       |
|                                      | Is options.uri set correctly in                              |
|                                      | /var/www/test/docroot/sites/default/local.drush.yml?         |
+--------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 


```

Good day all, i am currently having an issue to get a proper working mutisite configuration using BLT 9. I have added the vhosts and the databases and users to `box/config.yml` ran `vagrant provision` to make the changes. I now ran `blt recipes:mutisite:init` and entered the information into the wizard. This creates a mutisite directory structure in `docroot/sites/example`. When i run `blt setup --define site=example` it is *not* installing into the secondary database i have created in DrupalVM but instead uses the default 'drupal' database. I have tried many different things based on what i have read from the online documentation but cannot seem to get a functioning multisite install with it's own proper drush alias linked to the second database. Am i missing something? Any help would be greatly appreciated, thank you.

**Comment by pcsukardi** [comment]
I have been trying to work on this and while doing so i noticed something. I am getting a confirmation through ansible tasks that the secondary database i configured in the `box/config.yml` file is created here: 
````
TASK [geerlingguy.mysql : Remove MySQL test database.] *************************
ok: [test]

TASK [geerlingguy.mysql : Ensure MySQL databases are present.] *****************
ok: [test] => (item={u'collation': u'utf8_general_ci', u'name': u'drupal', u'encoding': u'utf8'})
ok: [test] => (item={u'collation': u'utf8_general_ci', u'name': u'drupal_two', u'encoding': u'utf8'})

TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************
ok: [test] => (item=None)
ok: [test] => (item=None)
````
but when i `vagrant ssh` into my machine to check for the databases i am met with this:
````
vagrant@test:/var/www/test$ mysql -u drupal -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 144
Server version: 5.7.21-0ubuntu0.16.04.1-log (Ubuntu)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| drupal             |
+--------------------+
2 rows in set (0.00 sec)
````
This sets me back even further in my efforts for a multi site setup -.- , i am completely new to this so _any_ advice would be truly and greatly appreciated.

**Comment by pcsukardi** [comment]
I tested this theory by logging in as the drupal-two user and running `SHOW DATABASES;` and no database is shown, only the information_schema. Doesn't drupalvm set the root password for mysql?

**Comment by timwood** [comment]
Documentation says it does, but apparently it doesn't. @geerlingguy Does Drupal VM set the mysql root password by default?

**Comment by pcsukardi** [comment]
Here is my `box/config.yml` file 
````
# Update the hostname to the local development environment hostname.
vagrant_hostname: wundea.local
vagrant_machine_name: wundea

# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 192.168.172.163

# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "Wundea"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/wundea
    type: nfs

drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/wundea"
drupal_core_path: "/var/www/wundea/docroot"
ssh_home: /var/www/wundea

#drupal_db_user: drupal
#drupal_db_password: drupal
#drupal_db_name: drupal

apache_vhosts:
  # Drupal VM's default domain, evaluating to whatever `vagrant_hostname` is set to (drupalvm.test by default).
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "example.wundea.local"
    documentroot: "/var/www/wundea/docroot"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

mysql_databases:
  - name: drupal
    encoding: utf8
    collation: utf8_general_ci
  - name: eia
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"
  - name: eia
    host: "%"
    password: eia
    priv: "eia.*:ALL"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - adminer
  - drush
  - mailhog
  - nodejs
  - selenium
  - xdebug

# PHP 5.6 (PHP 7.1 is being tested, see: https://docs.acquia.com/node/25726).
php_version: "5.6"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"

post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
````
*note

This is my `box/config.yml` file for BLT 8, i have been trying to get a successful multi site config for almost two weeks now, it seems where BLT 8 fails BLT 9 picks up, but than BLT 9 fails for some things (the config.yml file _not_ creating the second database)

here is my BLT 9 `box/config.yml`
````
# Update the hostname to the local development environment hostname.
vagrant_hostname: test.local
vagrant_machine_name: test

# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 192.168.98.100

# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604
workspace: /root

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "Tested8"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/test
    type: nfs

drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/test"
drupal_core_path: "/var/www/test/docroot"
ssh_home: /var/www/test

# Multisite installations should configure additional domains here.
apache_vhosts:
  # Drupal VM's default domain, evaluating to whatever `vagrant_hostname` is set to (drupalvm.dev by default).
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "example.{{ drupal_domain }}"
    documentroot: "/var/www/test/docroot"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Multisite installations should configure additional databases here.
mysql_databases:
  - name: drupal
    encoding: utf8
    collation: utf8_general_ci
  - name: test
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"
  - name: test
    host: "%"
    password: test
    priv: "drupal-two.*:ALL"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "9.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras: [adminer, selenium, drush, mailhog, memcached, nodejs, solr, xdebug]

# PHP 7
php_version: "7.1"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"

# Acquia Search defaults to 4.5.1.
#solr_version: "4.5.1"

post_provision_scripts:
#  - "../../../acquia/blt/scripts/drupal-vm/configure-solr.sh"
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.php"
````
When setting up for multi site with BLT 9 (second config.yml) i opted to use the new wizard command `blt recipes:multisite:init` but did _not_ have it edit my config.yml file (as this throws the entire formatting off) i instead just mirrored the info that i added into my config.yml file manually to align with what i was inputting when prompted by the wizard.

**Comment by pcsukardi** [comment]
As of right now this is my complete config for my multisite setup on BLT 9:

`box/config.yml`:
````
vagrant_hostname: test.local
vagrant_machine_name: test

# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 192.168.98.100

# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604
workspace: /root

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "Tested8"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/test
    type: nfs

drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/test"
drupal_core_path: "/var/www/test/docroot"
ssh_home: /var/www/test

# Multisite installations should configure additional domains here.
apache_vhosts:
  # Drupal VM's default domain, evaluating to whatever `vagrant_hostname` is set to (drupalvm.dev by default).
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "example.test.local"
    documentroot: "/var/www/test/docroot"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Multisite installations should configure additional databases here.
mysql_databases:
  - name: drupal
    encoding: utf8
    collation: utf8_general_ci
  - name: test
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"
  - name: test
    host: "%"
    password: test
    priv: "test.*:ALL"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "9.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras: [adminer, selenium, drush, mailhog, memcached, nodejs, solr, xdebug]

# PHP 7
php_version: "7.1"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"

# Acquia Search defaults to 4.5.1.
#solr_version: "4.5.1"

post_provision_scripts:
#  - "../../../acquia/blt/scripts/drupal-vm/configure-solr.sh"
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.php"
````
Here is my `blt/blt.yml` file
````
project:
  prefix: T
  human_name: test
  profile:
    name: standard
  local: {  }
git:
  default_branch: master
  remotes: {  }
drush:
  aliases:
    ci: self
  default_alias: '${default.alias.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
cm:
  strategy: config-split
````
Here is my site specific `blt.yml` file
````
project:
  local:
    hostname: example.test.local
    protocol: http
  machine_name: example
  human_name: example
drush:
  aliases:
    local: self
    remote: example.local
setup.strategy: install
````
Here is my `local.drush.yml`
````
options:
  uri: 'http://example.test.local'
````
Here is the active content in my `docroot/sites/sites.php` file:
````
$sites['example.test.local'] = 'example';
$sites['test.local'] = 'default';
````
Here is my `docroot/sites/example/settings/local.settings.php` file:
````
<?php

/**
 * @file
 * Local development override configuration feature.
 */

use Drupal\Component\Assertion\Handle;

$db_name = 'test';
if (isset($acsf_site_name)) {
  $db_name .= '_' . $acsf_site_name;
}

/**
 * Database configuration.
 */
$databases = array(
  'default' =>
  array(
    'default' =>
    array(
      'database' => $db_name,
      'username' => 'test',
      'password' => 'test',
      'host' => 'localhost',
      'port' => '3306',
      'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);

$dir = dirname(DRUPAL_ROOT);

// Use development service parameters.
$settings['container_yamls'][] = $dir . '/docroot/sites/development.services.yml';
$settings['container_yamls'][] = $dir . '/docroot/sites/blt.development.services.yml';

// Allow access to update.php.
$settings['update_free_access'] = TRUE;

/**
 * Assertions.
 *
 * The Drupal project primarily uses runtime assertions to enforce the
 * expectations of the API by failing when incorrect calls are made by code
 * under development.
 *
 * @see http://php.net/assert
 * @see https://www.drupal.org/node/2492225
 *
 * If you are using PHP 7.0 it is strongly recommended that you set
 * zend.assertions=1 in the PHP.ini file (It cannot be changed from .htaccess
 * or runtime) on development machines and to 0 in production.
 *
 * @see https://wiki.php.net/rfc/expectations
 */
assert_options(ASSERT_ACTIVE, TRUE);
Handle::register();

/**
 * Show all error messages, with backtrace information.
 *
 * In case the error level could not be fetched from the database, as for
 * example the database connection failed, we rely only on this value.
 */
$config['system.logging']['error_level'] = 'verbose';

/**
 * Disable CSS and JS aggregation.
 */
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;

/**
 * Disable the render cache (this includes the page cache).
 *
 * Note: you should test with the render cache enabled, to ensure the correct
 * cacheability metadata is present. However, in the early stages of
 * development, you may want to disable it.
 *
 * This setting disables the render cache by using the Null cache back-end
 * defined by the development.services.yml file above.
 *
 * Do not use this setting until after the site is installed.
 */
// $settings['cache']['bins']['render'] = 'cache.backend.null';
/**
 * Disable Dynamic Page Cache.
 *
 * Note: you should test with Dynamic Page Cache enabled, to ensure the correct
 * cacheability metadata is present (and hence the expected behavior). However,
 * in the early stages of development, you may want to disable it.
 */
// $settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
/**
 * Allow test modules and themes to be installed.
 *
 * Drupal ignores test modules and themes by default for performance reasons.
 * During development it can be useful to install test extensions for debugging
 * purposes.
 */
$settings['extension_discovery_scan_tests'] = FALSE;


/**
 * Configure static caches.
 *
 * Note: you should test with the config, bootstrap, and discovery caches enabled to 
 * test that metadata is cached as expected. However, in the early stages of development,
 * you may want to disable them. Overrides to these bins must be explicitly set for each 
 * bin to change the default configuration provided by Drupal core in core.services.yml. 
 * See https://www.drupal.org/node/2754947
 */

 // $settings['cache']['bins']['bootstrap'] = 'cache.backend.null';
 // $settings['cache']['bins']['discovery'] = 'cache.backend.null';
 // $settings['cache']['bins']['config'] = 'cache.backend.null';


/**
 * Enable access to rebuild.php.
 *
 * This setting can be enabled to allow Drupal's php and database cached
 * storage to be cleared via the rebuild.php page. Access to this page can also
 * be gained by generating a query string from rebuild_token_calculator.sh and
 * using these parameters in a request to rebuild.php.
 */
$settings['rebuild_access'] = FALSE;

/**
 * Temporary file path:
 *
 * A local file system path where temporary files will be stored. This
 * directory should not be accessible over the web.
 *
 * Note: Caches need to be cleared when this value is changed.
 *
 * See https://www.drupal.org/node/1928898 for more information
 * about global configuration override.
 */
$config['system.file']['path']['temporary'] = '/tmp';

/**
 * Private file path.
 */
$settings['file_private_path'] = $dir . '/files-private';
if (isset($acsf_site_name)) {
  $settings['file_public_path'] = "sites/default/files/$acsf_site_name";
  $settings['file_private_path'] = "$repo_root/files-private/$acsf_site_name";
}

/**
 * Trusted host configuration.
 *
 * See full description in default.settings.php.
 */
$settings['trusted_host_patterns'] = array(
  '^.+$',
);
````
Here is what i have at the bottom of my `docroot/sites/example/settings.php` file:
````
require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";
$settings['install_profile'] = 'standard';
````
After checking all these configs i `vagrant ssh` into the machine and run `blt setup --define site=example` and these are the results:
````
Setting up local environment for site example.
Using drush alias @${default.alias.local}
> source:build
> tests:behat:init:config
> source:build:composer
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> blt:init:git-hooks
Installing pre-commit git hook...
Installing commit-msg git hook...
> blt:init:settings
> source:build:frontend
> source:build:frontend-reqs
> source:build:frontend-assets
> drupal:hash-salt:init
Hash salt already exists.
> drupal:install
[error]  Invalid drush alias '@${default.alias.local}'. 
[error]  Invalid drush alias '@${default.alias.local}'. 
[error]  Command `drupal:install ` exited with code 1. 
````
@timwood is any of this congruent to your setup? @geerlingguy does _any_ of this seem off to your experienced eye in regards to multi site setup?

If BLT 9 is not stable enough yet to have a multisite configuration, would i go about the same config for BLT 8? What real deltas are there between the two for this kind of situation? I know i am asking a lot but i am new to this field and am trying to get my chops up so that I one day can help other newcomers. Thank you guys for giving me the time.

**Comment by timwood** [comment]
Not sure what `workspace:` is in your `box/config.yml`.
cm.strategy defaults to config-split, so you shouldn't need that in `blt/blt.yml`.

Try adding the multisite array to `blt/blt.yml`:
```
multisites:
  - default
  - example
```

You'll want a site-specific blt.yml for BOTH sites, even if a site is in the `docroot/sites/default` folder.

BLT 8.x does not really support multisite, so you'll need to stick with 9.x.

After making the changes above, when inside the VM, run `blt setup` which should perform all the tasks to setup the codebase and install/sync the default/first site. Then run `blt drupal:install --site=example` to install the example/second site. With BLT 9.x site became a full option passed directly with `--site=` rather than via `--define`.

**Comment by pcsukardi** [comment]
I do not know about that `workspace: /root` either, this is how the `box/config.yml` was created when i ran `blt vm`, i am going to try what you suggested and will post results. Thanks again man!

**Comment by theneonlobster** [comment]
I fixed this with the following:
```
mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"
```
Should read:
```
mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "*.*:ALL"
```

**Comment by pcsukardi** [comment]
I have made all the necessary changes as outlined above but to no avail, it does not want to use this drush variable set. It works when i change the `default_alias:` line to `self` but this causes a url issue when running `drush @self uli`.  

Here are my results when attempting and install:
````
vagrant@mysite:/var/www/test$ blt setup
Setting up local environment for site default.
Using drush alias @${drush.alias.local}
> source:build
> tests:behat:init:config
> source:build:composer
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> blt:init:git-hooks
Installing pre-commit git hook...
Installing commit-msg git hook...
> blt:init:settings
> source:build:frontend
> source:build:frontend-reqs
> source:build:frontend-assets
> drupal:hash-salt:init
Hash salt already exists.
> drupal:install
[error]  Invalid drush alias '@${drush.alias.local}'. 
[error]  Invalid drush alias '@${drush.alias.local}'. 
[error]  Command `drupal:install ` exited with code 1. 
````
and when i run `blt drupal:install --site=mysite2`
````
vagrant@mysite:/var/www/test$ blt drupal:install --site=mysite2
[error]  Invalid drush alias '@${drush.alias.local}'. 
[error]  Invalid drush alias '@${drush.alias.local}'. 
````
this variable was set in `blt/blt.yml` by default so i do not understand why it would be failing now.

**Comment by timwood** [comment]
I was getting this same thing a few days ago and I believe destroying and relaunching the DrupalVM helped. Outside the VM: `vagrant destroy` then `vagrant up`

**Comment by pcsukardi** [comment]
Tried `vagrant destroy` followed by `vagrant up` still getting these results:
````
Setting up local environment for site default.
Using drush alias @${drush.alias.local}
> source:build
> tests:behat:init:config
> source:build:composer
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> blt:init:git-hooks
Installing pre-commit git hook...
Installing commit-msg git hook...
> blt:init:settings
> source:build:frontend
> source:build:frontend-reqs
> source:build:frontend-assets
> drupal:hash-salt:init
Hash salt already exists.
> drupal:install
[error]  Invalid drush alias '@${drush.alias.local}'. 
[error]  Invalid drush alias '@${drush.alias.local}'. 
[error]  Command `drupal:install ` exited with code 1. 
````
Maybe i have to scrap the entire project and re build? I am kind of lost at this point, it seems the only issue i have left is getting proper drush aliases. @timwood how does _your_ `blt/blt.yml` file look?

**Comment by pcsukardi** [comment]
After reviewing @theneonlobster https://github.com/theneonlobster/eedplatek `blt/blt.yml` file i noticed my variable was not set correctly. it read `${drush.alias.local}` when it should have read `${drush.aliases.local}` i fixed this issue and i am re provisioning now, hopefully i will be back blowing horns!

**Comment by pcsukardi** [comment]
:tada: I got it to work! It is somewhat unorthodox however. I was _still_ unable to run `drush @self uli` and get a proper link to my site so what i did was wait for the install to finish, open up my browser and navigate to my sites URL. When brought to the landing page i chose to login and entered the credentials that are generated after running `blt setup` and voila brought to the config page! I also had to do this for the second site because when i ran `drush @mysite2 uli` it brought me to a landing page asking me to purchase a domain for mysite2.com. I do not know what is up with accessing the site through the drush aliases set but at least i have a multi site up and running! @timwood, @theneonlobster, @geerlingguy thank you so much for assisting me with this issue i truly appreciate it.

**Comment by pcsukardi** [comment]
Before i close this issue i would like to leave the result of running `blt doctor` on both my sites, i will investigate into these errors but will leave it here for posterity and maybe a frame of reference to others having similar issues.
````
vagrant@mysite:/var/www/test$ blt doctor 
+---------------------------+-----------------------------------------------------+
| Property                  | Value                                               |
+---------------------------+-----------------------------------------------------+
| %paths.%root              | /var/www/test/docroot                               |
| %paths.%site              | sites/default                                       |
| %paths.%modules           | sites/all/modules                                   |
| %paths.%themes            | sites/all/themes                                    |
| %paths.%config-sync       | /var/www/test/config/default                        |
| %paths.%files             | sites/default/files                                 |
| %paths.%temp              | /tmp                                                |
| %paths.%private           | /var/www/test/files-private                         |
| admin-theme               | seven                                               |
| alias-searchpaths.0       | /var/www/test/drush/sites                           |
| blt-version               | 9.0.5                                               |
| bootstrap                 | Successful                                          |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17          |
| config-sync               | /var/www/test/config/default                        |
| db-driver                 | mysql                                               |
| db-hostname               | localhost                                           |
| db-name                   | drupal                                              |
| db-password               | drupal                                              |
| db-port                   | 3306                                                |
| db-status                 | Connected                                           |
| db-username               | drupal                                              |
| drupal-settings-file      | sites/default/settings.php                          |
| drupal-version            | 8.5.1                                               |
| drush-alias-files.0       | /var/www/test/drush/sites/default.site.yml          |
| drush-alias-files.1       | /var/www/test/drush/sites/example.site.yml          |
| drush-alias-files.2       | /var/www/test/drush/sites/mysite2.site.yml          |
| drush-alias-files.3       | /var/www/test/drush/sites/test.site.yml             |
| drush-conf.0              | /var/www/test/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/test/drush/drush.yml                       |
| drush-conf.2              | /var/www/test/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/test/vendor/bin/drush                      |
| drush-temp                | /tmp                                                |
| drush-version             | 9.2.1                                               |
| files                     | sites/default/files                                 |
| install-profile           | standard                                            |
| modules                   | sites/all/modules                                   |
| php-bin                   | /usr/bin/php7.1                                     |
| php-conf.0                | /etc/php/7.1/cli/php.ini                            |
| php-os                    | Linux                                               |
| private                   | /var/www/test/files-private                         |
| root                      | /var/www/test/docroot                               |
| site                      | sites/default                                       |
| stacks.drupal-vm.inited   | true                                                |
| stacks.dev-desktop.inited | false                                               |
| temp                      | /tmp                                                |
| theme                     | bartik                                              |
| themes                    | sites/all/themes                                    |
| uri                       | http://www.test.local                               |
+---------------------------+-----------------------------------------------------+
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri          | base_url in tests/behat/local.yml does not match the site    |
|                                      | URI.                                                         |
|                                      |   Behat base_url is set to                                   |
|                                      | http://local.test.com.                                       |
|                                      |   Drush site URI is set to                                   |
|                                      | http://www.test.local.                                       |
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse         | Did not get a response from http://www.test.local            |
|                                      | Is your *AMP stack running?                                  |
|                                      | Is your /etc/hosts file correctly configured?                |
|                                      | Is your web server configured to serve this URI from         |
|                                      | /var/www/test/docroot?                                       |
|                                      | Is options.uri set correctly in                              |
|                                      | /var/www/test/docroot/sites/default/local.drush.yml?         |
+--------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
vagrant@mysite:/var/www/test$ blt doctor --site=mysite2
+---------------------------+-----------------------------------------------------+
| Property                  | Value                                               |
+---------------------------+-----------------------------------------------------+
| %paths.%root              | /var/www/test/docroot                               |
| %paths.%site              | sites/mysite2                                       |
| %paths.%modules           | sites/all/modules                                   |
| %paths.%themes            | sites/all/themes                                    |
| %paths.%config-sync       | /var/www/test/config/default                        |
| %paths.%files             | sites/mysite2/files                                 |
| %paths.%temp              | /tmp                                                |
| %paths.%private           | /var/www/test/files-private                         |
| admin-theme               | seven                                               |
| alias-searchpaths.0       | /var/www/test/drush/sites                           |
| blt-version               | 9.0.5                                               |
| bootstrap                 | Successful                                          |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17          |
| config-sync               | /var/www/test/config/default                        |
| db-driver                 | mysql                                               |
| db-hostname               | localhost                                           |
| db-name                   | test                                                |
| db-password               | test                                                |
| db-port                   | 3306                                                |
| db-status                 | Connected                                           |
| db-username               | test                                                |
| drupal-settings-file      | sites/mysite2/settings.php                          |
| drupal-version            | 8.5.1                                               |
| drush-alias-files.0       | /var/www/test/drush/sites/default.site.yml          |
| drush-alias-files.1       | /var/www/test/drush/sites/example.site.yml          |
| drush-alias-files.2       | /var/www/test/drush/sites/mysite2.site.yml          |
| drush-alias-files.3       | /var/www/test/drush/sites/test.site.yml             |
| drush-conf.0              | /var/www/test/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/test/drush/drush.yml                       |
| drush-conf.2              | /var/www/test/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/test/vendor/bin/drush                      |
| drush-temp                | /tmp                                                |
| drush-version             | 9.2.1                                               |
| files                     | sites/mysite2/files                                 |
| install-profile           | standard                                            |
| modules                   | sites/all/modules                                   |
| php-bin                   | /usr/bin/php7.1                                     |
| php-conf.0                | /etc/php/7.1/cli/php.ini                            |
| php-os                    | Linux                                               |
| private                   | /var/www/test/files-private                         |
| root                      | /var/www/test/docroot                               |
| site                      | sites/mysite2                                       |
| stacks.drupal-vm.inited   | true                                                |
| stacks.dev-desktop.inited | false                                               |
| temp                      | /tmp                                                |
| theme                     | bartik                                              |
| themes                    | sites/all/themes                                    |
| uri                       | mysite2                                             |
+---------------------------+-----------------------------------------------------+
PHP Notice:  Undefined index: host in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 60

Notice: Undefined index: host in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 60
PHP Notice:  Undefined index: root in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 81

Notice: Undefined index: root in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 81
PHP Notice:  Undefined index: root in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 84

Notice: Undefined index: root in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 84
PHP Notice:  Undefined index: root in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 86

Notice: Undefined index: root in /var/www/test/vendor/acquia/blt/src/Robo/Commands/Doctor/DrupalVmCheck.php on line 86
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri          | base_url in tests/behat/local.yml does not match the site    |
|                                      | URI.                                                         |
|                                      |   Behat base_url is set to                                   |
|                                      | http://local.test.com.                                       |
|                                      |   Drush site URI is set to mysite2.                          |
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| DrupalVmCheck:checkUri:uri           | uri for @@mysite2.local drush alias does not match           |
|                                      | vagrant_hostname for DrupalVM.                               |
|                                      |   uri is set to mysite2 for @@mysite2.local                  |
|                                      |   vagrant_hostname is set to mysite.local for DrupalVM.      |
|                                      |   mysite2 != mysite.local                                    |
| DrupalVmCheck:checkRoot:root         | root for @@mysite2.local drush alias does not match docroot  |
|                                      | for DrupalVM.                                                |
|                                      |   root is set to  for @@mysite2.local                        |
|                                      |   docroot is set to /var/www/test/docroot for DrupalVM.      |
|                                      |    != /var/www/test/docroot                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse         | Did not get a response from mysite2                          |
|                                      | Is your *AMP stack running?                                  |
|                                      | Is your /etc/hosts file correctly configured?                |
|                                      | Is your web server configured to serve this URI from         |
|                                      | /var/www/test/docroot?                                       |
|                                      | Is options.uri set correctly in                              |
|                                      | /var/www/test/docroot/sites/mysite2/local.drush.yml?         |
+--------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
````

**Comment by pcsukardi** [comment]
I have found the fix for my drush issue. The link was being broken; when running `drush @self uli` i was getting a crazy www.default.com url popping up from the link being created. The remedy for this was to specify the uri in the `local.drush.yml` file as such `drush @self uli --uri=http://www.mysite.local`, this will resolve the broken link issue.
